<a href="https://colab.research.google.com/github/Felipehl04/CODES-OF-DATA-VISTUALIZATION-/blob/main/03_DataStructures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1. What is a DS?**

A DS is an object that let us store more than one value.

Formally, a DS is **sequence** of values which can be localted whit an index. 


# **2. linear algebra**

## 2.1 What is Numpy?

Numpy ( Numerical Python) is a collection of functiosn and methods.

In [1]:
# Install the library 
import numpy as np

2.2 Numpy arrays - vectors and matrices

*Example 1 - colum vector*


 

In [6]:
 a = np.array([[1],[2],[3]])
 print(a)
 print(a.shape)

[[1]
 [2]
 [3]]
(3, 1)


*Example 2 - Row vector 

In [11]:
b = np.array([[4,5,6]])
print(b)
print(b.shape)

[[4 5 6]]
(1, 3)


*Example 3 - Matrix*

In [14]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [25]:
# nice trick

nf, nc = M.shape


#  2.3. Scilling

to acces ir several elements of then object.


In [36]:
# Extract the first element

##Column vector 
print(a[0,0])

##Row vector
print(b[0,0,])


##Matrix 
print(M[0,0,])

1
4
1


In [39]:
# Extrac the last element

##Column vector 
print(a[-1,0])

##Row vector
print(b[0,-1,])

##Matrix 
print(M[-1,-1,])

3
6
9


In [43]:
# Extract a subset

##Column vector 
print(a[0:2])

##Row vector
print(b[0,0:2])

##Matrix 
print(M[0:2,0:2])

[[1]
 [2]]
[4 5]
[[1 2]
 [4 5]]


# 2.4. Methods 

In [47]:
#Zeros 
z1= np.zeros(4)
print(z1)

z2=np.zeros((3,2))
print(z2)




[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [50]:
#Ones
o1= np.ones(4)
print(o1)

o2=np.ones((3,2))
print(o2)


[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[5., 5.],
       [5., 5.],
       [5., 5.]])

**ANOTHER CREATION OPTIONS**

In [52]:
# FUll

f = np.full((3,2),5)
print(f)

[[5 5]
 [5 5]
 [5 5]]


In [61]:
# Linear sequence 

np.arange(6)
np.arange(23,33)
np.arange(23,33,0.5)

array([23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5])

In [62]:
# Linear space

np.linspace(15,90,6)

array([15., 30., 45., 60., 75., 90.])

## 2.5. Random Numbers

In [80]:
# A Single Value - between 0 y 1
np.random.seed(1234)
np.random.rand()

0.1915194503788923

In [86]:
# Example - Toss a coin

if np.random.rand() < 0.5:
  print("head")
else:
  print("Tails")



head


In [114]:
#Two heads in a row

if np.random.rand() < 0.25:
  print("YOU WIN!")
else:
  print("YOU LOUSE!")



YOU WIN!


In [153]:
#Two heads in a row
ft = np.random.rand()
if ft < 0.5:
  print("The first toss was head")
else:
  print("The first toss was Tails")

st = np.random.rand()
if st < 0.5:
  print("The second toss was head")
else:
  print("The second toss was Tails")

  if ft < 0.5 and st < 0.5:
    print("YOU WIN!")
  else:
    print("YOU LOSE!")

The first toss was Tails
The second toss was Tails
YOU LOSE!
